spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/notification
    username: root

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
    show-sql: true
